### ISSUE TITLE
gexporter for iOS

### ISSUE THREAD

**Issue by alinradut** [gimportexportdevs/gimporter#1]
I wrote a simple iOS app that serves GPX/FIT files for gimporter, it's available here: https://github.com/clawoo/gexporter-ios

Feel free to add it to this repo.

I only tested it against the Fenix 5 simulator because I only have a Fenix 3HR (and was secretly hoping it would work, but of course it doesn't).

The iOS version probably won't be posted to the AppStore because the app is not complex enough to pass Apple's review process.

**Comment by haraldh** [comment]
added to the README
