### ISSUE TITLE
No connection since Garmin Connect 4.20

### ISSUE THREAD

**Issue by usrusr** [gimportexportdevs/gimporter#4]
As already stated numerous times on the cIQ store, connectivity is broken since Connect for Android 4.20. Issue opened for better communication. 

Apparently, 4.20 has incremented the targetSdkVersion to 28, at which Android enforces https for all outgoing connections from the app (which requests from http://localhost on behalf of gimporter) unless explicitly declared in the manifest. 

It's up to Garmin to declare that exception and I don't think gimporter/gexporter can do anything about it other than waiting and maybe nagging Garmin (a request from the author of one of the most popular cIQ things might pull some weight), unless there is a way of serving local https to a third party app (I don't think that this is possible)

**Comment by haraldh** [comment]
https://forums.garmin.com/developer/connect-iq/f/discussion/167402/breakage-of-makewebrequest-from-http-localhost

**Comment by usrusr** [comment]
Garmin is allowing plain http to localhost since 4.22
