### ISSUE TITLE
Gimporter without Garmin Mobile Connect App

### ISSUE THREAD

**Issue by user135480** [gimportexportdevs/gimporter#5]
Hi,
I'm using Edge Explore. Smartphone was paired. Connection worked fine having Garmin Mobile Connect App installed on the smartphone.
Now I decided to change to lightweight gexporter/gimporter apps just to handle route upload to Edge.
I have removed Garmin Mobile Connect App.
Having no Garmin Mobile Connect App on the phone, bluetooth connection is not estabilished between my Edge Explore and smartphone, so gimporter on Edge says all the time "Waiting for bluetooth" despite runing gexporter on smartphone. Looks like gexporter doesn't open connection to Edge over bluetooth in similar way like Garmin Mobile Connect App does.
Does this app work over bluetooth with no haevy Garmin Connect Mobile App installed on the smartphone?
Thanks

**Comment by haraldh** [comment]
Garmin connect mobile app has to be installed... Sorry... Garmin does not give us the possibility for more advanced apps


Am 13. September 2019 12:30:11 MESZ schrieb user135480 <notifications@github.com>:
