### ISSUE TITLE
supporting 2 connected devices

### ISSUE THREAD

**Issue by telemaxx** [gimportexportdevs/gimporter#6]
i successfully use the widget on my fenix5s

now i have also an edge 530.
the widget i can install, but it is not shown on the edge at all.

the app i can install and start, but mostly it did not connect to the companion app.
on my fenix it is still working.

i think the problem is, that i have 2 devices connected to the garmin app and youre app using the first device ?

Maybe you can have a look.

Thanks in advance,
Thomas

**Comment by haraldh** [comment]
There should be no problem regarding two devices. The bug is on the edge 530.

Do you have bluetooth enabled on the 530?

btw, the widget on the 530 should be in the drop down menu (where you enable wifi, bluetooth, swipe left or right)

**Comment by telemaxx** [comment]
Hi Harald,
> There should be no problem regarding two devices. The bug is on the edge 530

Then i had investigated in the wrong direction.
Now i have some new findings

1. The Problem with the not visible widget:
This is really an edge bug.
if i have only gimported as widget installed, i see the button "widget", but a click on it did not open something.
So i install additionally the default "notification" widget. Now i see both widgets. strange.
Than i did a crosscheck and uninstall gimporter, so only notification widget is installed.
this is still working properly.

2. The problem with no connection to the companion app:
There i found also a solution.
fenix was always working, edge only sometimes.
and what is the difference between them?
the edge has wifi.
if i switch of wifi on my edge, i get a connection. app and widget.
seems so that the edge is looking on the wrong interface.

Thanks for the support,
Thomas
