### ISSUE TITLE
Include support for 920xt

### ISSUE THREAD

**Issue by kevin-exo** [gimportexportdevs/gimporter#8]
Hi all,

I recently [discovered ](http://runningbadger.blogspot.com/2015/08/a-tool-to-help-with-navigation-on.html) that the forerunner 920xt (and fenix 3) can do proper turn-by-turn navigation if the route is exported to .fit format (ridewithgps and plotaroute do it).

Any chance this tool can be ported to the 920xt? I think the different screen format and/or IQ supported version could be a problem, but I'll be able to do some testing, if that helps.

Thanks in advance!

**Comment by haraldh** [comment]
I am sorry, gimporter needs at least connectiq version 2.2.0 to even work ... the 920xt only supports 1.3.1, AFAIK

**Comment by kevin-exo** [comment]
> 
> 
> I am sorry, gimporter needs at least connectiq version 2.2.0 to even work ... the 920xt only supports 1.3.1, AFAIK

Ouch >.<. It's actually 1.4.5 on the latest update (https://www8.garmin.com/support/download_details.jsp?id=7249), but I guess it doesn't make a difference, does it?
Edit: No, it doesn't ("sending files to device" was one of the new features that came with IQ 2.0... :( ([source](https://www.dcrainmaker.com/2016/10/connect-iq-2-2.html))

Thanks for the quick reply ;)
