### ISSUE TITLE
Download tracks without internet access on Garmin Edge 530 + Android

### ISSUE THREAD

**Issue by lumixen** [gimportexportdevs/gimporter#9]
Hey @haraldh 

First of all thank you very much for this awesome app, it truly enhances my bike touring experience with garmin device.

There is one thing that puzzles me a bit. Whenever I try to download GPX/FIT tracks without active internet connection on mobile device - widget fails with `Download failed` message. Though get list of tracks works just fine without internet connection.
Both actions use `makeWebRequest` but obviously one downloads JSON while other requests `HTTP_RESPONSE_CONTENT_TYPE_FIT`/`HTTP_RESPONSE_CONTENT_TYPE_GPX`.

I wonder if offline track download was working in the past and it was broken at some point by Garmin/their SDK  update or import never worked before without active internet connection? Or perhaps it works for some devices and doesn't for others?

Thanks in advance!

**Comment by haraldh** [comment]
The Connect IQ `makeWebRequest` is proxied via the Connect App on the phone to the web address. Although `gimporter` requests from `localhost` (which is the phone), the Connect App just errors the `makeWebRequest`, if the phone has no internet access. It does not even try. This regression was introduced after they fixed the [`localhost` regression](https://forums.garmin.com/developer/connect-iq/f/discussion/167402/breakage-of-makewebrequest-from-http-localhost).

**Comment by lumixen** [comment]
I see, thanks 👍 
But still though, why 
```
Comm.makeWebRequest("http://127.0.0.1:22222/dir.json", { "type" => mGPXorFIT, "short" => "1", "longname" => "1" },
                                {
                                    :method => Comm.HTTP_REQUEST_METHOD_GET,
                                        :headers => {
                                        "Content-Type" => Comm.REQUEST_CONTENT_TYPE_JSON
                                    },
                                        :responseType => Comm.HTTP_RESPONSE_CONTENT_TYPE_JSON
                                             }, method(:onReceiveTracks)
                );
```
doesn't fail without internet connection? Both request localhost, but the one that requests tracks list works just fine without internet connection 🤔

**Comment by haraldh** [comment]
oh... hmm, good point

**Comment by haraldh** [comment]
In my Android logs, I can see the track list request, but not the other one.

So, it seems like the Garmin Connect App makes a distinction between `HTTP_RESPONSE_CONTENT_TYPE_JSON` and `HTTP_RESPONSE_CONTENT_TYPE_FIT`

I think you have to bother Garmin.

**Comment by lumixen** [comment]
> 
> 
> In my Android logs, I can see the track list request, but not the other one.
> 
> So, it seems like the Garmin Connect App makes a distinction between `HTTP_RESPONSE_CONTENT_TYPE_JSON` and `HTTP_RESPONSE_CONTENT_TYPE_FIT`
> 
> I think you have to bother Garmin.

Yeah, that was my initial thought. Thank you for checking it up!
There is one more difference between these requests - track list request passes header Content-Type `headers => { "Content-Type" => Comm.REQUEST_CONTENT_TYPE_JSON }` while track download doesn't. But to be honest I doubt that it makes any difference..
P.S. It feels like Garmin intentionally tries to make their navigation features in cycling devices very limited without internet connection.

**Comment by haraldh** [comment]
I tried with the Content Header set.. makes no difference

**Comment by haraldh** [comment]
Closing, as I can't do anything here.

**Comment by Phaet** [comment]
I struggled a lot with the same issue and wondered why it doesn't work at home. I found that it fails when the phone is connected via Wifi. When connecting via mobile data, it works, though.
